package com.utc.cards.model.game;

public enum GameStep
{
    DETERMINATE_FIRST_PLAYER, DISTRIBUTE, GIVE_PLAYER_TURN, DETERMINATE_SCORE, DETERMINATE_WINNER, END_GAME, ASK_EXCHANGE, WAIT, DO_EXCHANGE
}
